# Generated by Django 3.2.16 on 2026-04-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Цена закупки в рублях', max_digits=10, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='розничная цена в рублях', max_digits=10, verbose_name='Цена продажи')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать товар на складе', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Категория')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name'],
            },
        ),
    ]
