# Generated by Django 3.2.16 on 2026-04-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('contact_info', models.CharField(help_text='Телефон, email, адрес, контактное лицо и т.д.', max_length=500, verbose_name='Контакты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('upload_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
    ]
