# Generated by Django 3.2.16 on 2026-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
