# Generated by Django 3.2.16 on 2026-04-07 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Актуально для прихода', max_digits=10, null=True, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Актуально для продажи', max_digits=10, null=True, verbose_name='Цена продажи')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('note', models.TextField(blank=True, help_text='Дополнительная информация об операции', verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='products.product', verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-operation_date'],
            },
        ),
    ]
