# Generated by Django 3.2.16 on 2026-04-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventoryoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='operation_type',
            field=models.CharField(choices=[('receipt', 'Приход'), ('sale', 'Продажа'), ('write_off', 'Списание'), ('inventory_adjustment', 'Корректировка')], default='receipt', max_length=50, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='inventoryoperation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryoperation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
